### ISSUE TITLE
小程序重启耗时过久，请确认业务逻辑中是否有复杂运算，或者死循环

### ISSUE THREAD

**Issue by BertramRay** [NanYuJun/ChatGTP-uni#6]
运行时小程序报错
message：小程序重启耗时过久，请确认业务逻辑中是否有复杂运算，或者死循环
appid: wxf2f03cad73922f50
openid: o6zAJs4Uhm-IuH2U0f1ls5VyJfGM
ideVersion: 1.05.2110110
osType: win32-x64
time: 2023-03-31 01:33:30

**Comment by NanYuJun** [comment]
目前没有复现，请提供完整问题截图和说明～

**Comment by NanYuJun** [comment]
已复现并处理
